DemoApp/Models/Department.cs
namespace DemoApp.Models
{
    public class Department
    {
        public int DepartmentId { get; set; }

        public string DepartmentName { get; set; }
        public bool isActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}

DemoApp/Models/Employee.cs
namespace DemoApp.Models
{
    public class Employee
    {
     public int EmployeeId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public DateTime HDate { get; set; }
        public decimal Salary  { get; set; }
        public bool isActive { get; set; }
        public bool IsDeleted { get; set; }

    }
}

DemoApp/Models/ErrorViewModel.cs
namespace DemoApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DemoApp/Controllers/EmployeesController.cs
using DemoApp.Data;
using DemoApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;

namespace DemoApp.Controllers
{
    public class EmployeesController : Controller
    {
        private AppDBContext db;
        public EmployeesController(AppDBContext _db)
        {
            db = _db;
        }
        static List<Employee> DeletedEmployees = new List<Employee>();
        
        

        public IActionResult Index()
        {
            
           ViewBag.count = db.Employees.Where(x => x.IsDeleted == true).Count();
            return View(db.Employees.Where(x=>x.IsDeleted==false).OrderByDescending(x=>x.HDate));
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Employee emp)
        {
            emp.isActive = true;
            db.Employees.Add(emp);
            db.SaveChanges();
            return RedirectToAction(nameof(Index));

        }

        [HttpGet]
        public IActionResult Details(int? id)
        {
            if (id==null)
            {
                return RedirectToAction(nameof(Index));
            }

            var empData = db.Employees.Find(id);
            if (empData != null)
            {
                //return RedirectToAction(nameof(Details),empData);
                return View(empData);
            }
            return RedirectToAction(nameof(Index));
        }


        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Index));
            }

            var empData = db.Employees.Find(id);
            if (empData != null)
            {
                //return RedirectToAction(nameof(Details),empData);
                return View(empData);
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public IActionResult Edit(Employee emp)
        {
                db.Update(emp);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
        }
        //this will work directly 
        //[HttpGet]
        //public IActionResult Delete(int? id)
        //{

        //    var emp = db.Employees.Find(id);

        //    if (emp != null && id!=null)
        //    {
        //        db.Employees.Remove(emp);
        //        db.SaveChanges();
        //        return View(emp);
        //    }
        //    else return RedirectToAction(nameof(Index));
        //}
        //------------------------------------------------------
        //this needs post 
        [HttpGet]
        public IActionResult Delete(int? id)
        {

            var emp = db.Employees.Find(id);

            if (emp != null && id != null)
            {
                return View(emp);
            }
            else return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult ConfirmDelete(Employee emp)
        {

            var empData = db.Employees.Find(emp.EmployeeId);

            if (empData != null)
            {
                db.Employees.Remove(empData);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            else
                return RedirectToAction(nameof(Index));
        }

        public IActionResult SoftDelete(int? id)
        {

            var emp = db.Employees.Find(id);

            if (emp != null &&  id != null)
            {
                DeletedEmployees.Add(emp);
                emp.IsDeleted = true;
                db.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            else return RedirectToAction(nameof(Index));
        }

        public IActionResult Active(int? id)
        {
            var emp = db.Employees.Find(id);
            if (emp != null && id != null)
            {
                emp.isActive = true;
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            else return RedirectToAction(nameof(Index));
        }

        public IActionResult Restore()
        {

            return View(DeletedEmployees);

        }

        [HttpPost]
        public IActionResult RestoreEmp()
        {
            foreach (var item in DeletedEmployees)
            {

                //item.IsDeleted = false;
                //Console.WriteLine(item);
                //db.Employees.Add(item);

                var existingEmp = db.Employees.FirstOrDefault(e => e.EmployeeId == item.EmployeeId);
                if (existingEmp != null)
                {
                    existingEmp.IsDeleted = false;
                    db.Update(existingEmp);
                    db.SaveChanges();
                }


            }


            // Clear static list after restore
            DeletedEmployees.Clear();

            return RedirectToAction(nameof(Index));
        }


    }
}

DemoApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using DemoApp.Models;

namespace DemoApp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

DemoApp/Views/Employees/Create.cshtml
@model Employee
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<form asp-action="Create" method="post">

    <table class="table table-bordered">
     
<tr>
    <td><label asp-for="Name"></label></td>
    <td> <input asp-for="Name" class="form-control" /></td>
</tr>

<tr>
    <td><label asp-for="Email"></label></td>
    <td> <input asp-for="Email" class="form-control" /></td>
</tr>
<tr>
    <td><label asp-for="HDate"></label></td>
    <td> <input asp-for="HDate" class="form-control" /></td>
</tr>
<tr>
    <td><label asp-for="Salary"></label></td>
    <td> <input asp-for="Salary" class="form-control" /></td>
</tr>

<tr>
    <td colspan="2">
		<input type="submit" value="Create" class="btn btn-success" />
		<a asp-action="Index" class="btn btn-danger">Cancel</a>
    </td>
	</tr>.
    </table>
</form>

DemoApp/Views/Employees/Delete.cshtml
@model Employee

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

@* <h1> Are you sure you want to delete @Model.Name employee?</h1> *@

@* <a asp-action="Delete" asp-controller="Employees" asp-route-id="@Model.EmployeeId" class="btn btn-outline-success">yes</a> *@
@* <a asp-route="AllEmployees" class="btn btn-outline-danger">no</a> *@

<h1>do you want to delete @Model.Name ?</h1>
<form method="post" asp-action="ConfirmDelete" asp-asp-controller="Employees">
	@Html.HiddenFor(x => x.EmployeeId)
	<input type="submit"  value="yes" class="btn btn-success" />
	<a asp-action="index" class="btn btn-outline-secondary">Cancel</a>
</form>

DemoApp/Views/Employees/Details.cshtml
@model Employee
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div class="container py-5">
    <div class="card mx-auto" style="max-width: 400px;">
        <div class="card-header text-center bg-primary text-white">
            @Model.Name's Details
        </div>
        <div class="card-body text-center">

            <h5 class="card-title mb-1">@Model.Name</h5>
            <ul class="list-unstyled mb-3">
                <li><strong>Salary:</strong> @Model.Salary </li>
                <li><strong>Email:</strong> @Model.Email</li>
            </ul>
            <p class="card-text">Employee Status:

				@if (Model.isActive)
				{
					<span class=" text-success" role="alert">Active</span>
				}
				else
				{
					<span class=" text-danger" role="alert">Non-Active</span>
				}
              </p>
        </div>
        <div class="card-footer text-muted text-center">
			Employee ID: @Model.EmployeeId
        </div>
    </div>
</div>

DemoApp/Views/Employees/Edit.cshtml
@model Employee
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>
<form asp-action="Edit" method="post">
	@Html.HiddenFor(x=>x.EmployeeId)
    <table class="table table-bordered">

        <tr>
            <td><label asp-for="Name"></label></td>
            <td> <input asp-for="Name" class="form-control" /></td>
        </tr>

        <tr>
            <td><label asp-for="Email"></label></td>
            <td> <input asp-for="Email" class="form-control" /></td>
        </tr>
        <tr>
            <td><label asp-for="HDate"></label></td>
            <td> <input asp-for="HDate" class="form-control" /></td>
        </tr>
        <tr>
            <td><label asp-for="Salary"></label></td>
            <td> <input asp-for="Salary" class="form-control" /></td>
        </tr>

        <tr>
            <td><label asp-for="isActive"></label></td>
            <td> <input asp-for="isActive"  class="form-check-input" /></td>
        </tr>

     

        <tr>
            <td colspan="2">
                <input type="submit" value="Save Changes" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-danger">Cancel</a>
            </td>
        </tr>.
    </table>
</form>

DemoApp/Views/Employees/Index.cshtml
@model IEnumerable<Employee>
@{
    ViewData["Title"] = "Index";
}


<div class="mx-auto">
	<h1 class="my-5">Employees</h1>
	<a asp-action="Create"
	   class="btn btn-primary">Create Employee</a>
	
	@if (ViewBag.count > 0)
	{
	<a asp-action="Restore"
	   class="btn btn-secondary">Restore Employee</a>
	}



	<div class="card " style="width: 60rem;">
		<table class="table table-striped">
			<tr>
				<th>@Html.DisplayNameFor(x=>x.Name)</th>
				<th>@Html.DisplayNameFor(x => x.Salary)</th>
				<th>@Html.DisplayNameFor(x => x.isActive)</th>
				<th>Operations</th>

			</tr>	
				
		 @if (Model.Any())
		 {
			@* <div class="alert alert-success" role="alert"> *@
			@* 	@Model.Count() Employees Found *@
			@* </div> *@


			@foreach (var emp in Model)
			{
				<tr>
					<td>@emp.Name</td>

					<td>@emp.Salary</td>
					

				
					@if (emp.isActive)
					{
						<td>
							<span class="alert alert-success p-1 fs-6 align-items-center" role="alert">
								Active
							</span>
						</td>
					}
					else
					{
							<td><span class="alert alert-danger p-1 fs-6 align-items-center" role="alert"> Non-Active</span></td>
					}
					<td>
					    <a asp-action="Details" asp-route-id="@emp.EmployeeId" class="btn btn-info">more details</a>
					    <a asp-action="Edit"  asp-route-id="@emp.EmployeeId" class="btn btn-secondary">Edit</a>
					    <a asp-action="Delete"  asp-route-id="@emp.EmployeeId" class="btn btn-danger">Delete</a>
						<a asp-action="SoftDelete" asp-route-id="@emp.EmployeeId" class="btn btn-danger">Soft Delete</a>
					</td>
				</tr>
			}
	     }
				else
				{
					<div class="alert alert-danger" role="alert">
						No Employees Found
					</div>
				}
		
		</table>

	</div>


</div>

DemoApp/Views/Employees/Restore.cshtml
@model IEnumerable<Employee>

@{
    ViewData["Title"] = "Restore";
}

<h1>Restore</h1>
<div class="mx-auto" >


	<div class="card " style="width: 60rem;">
		<table class="table table-striped">
			<tr>
				<th>@Html.DisplayNameFor(x => x.Name)</th>
				<th>@Html.DisplayNameFor(x => x.Salary)</th>
				<th>@Html.DisplayNameFor(x => x.isActive)</th>
			

			</tr>
			@if (Model.Any())
			{
				<form asp-action="RestoreEmp" asp-controller="Employees" method="post" class="mt-4">
				
				<button type="submit" class="btn btn-success">Restore Employee</button>
				</form>
	@foreach (var emp in Model)
	{
		<tr>
			<td>@emp.Name</td>

			<td>@emp.Salary</td>



			@if (emp.isActive)
			{
				<td>
					<span class="alert alert-success p-1 fs-6 align-items-center" role="alert">
						Active
					</span>
				</td>
			}
			else
			{
				<td><span class="alert alert-danger p-1 fs-6 align-items-center" role="alert"> Non-Active</span></td>
			}
		
		</tr>
	}

}
else
{
	<div class="alert alert-danger" role="alert">
		No Employees Found
	</div>
}



	</table>
</div>
</div>

DemoApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DemoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoApp</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DemoApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - DemoApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>